import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/header';
import PaginationTes from '../components/styles/pagination';
// import Image from 'next/image';
// import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vihara Buddha Manggala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="../styles/dist/output.css" />
      </Head>
      <PaginationTes />
    </div>
  );
};

export default Home;
